version: "3.8"
services:
    postgres:
        image: postgres:13.2
        container_name: seal-bot-postgres
        ports:
          - 15432:5432
        volumes:
          - ./postgres/data:/var/lib/postgresql/data/
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        restart: always
    
